// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: proto/api/v1alpha1/url_shortener.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A request of shortening a number of URLs
type URLShortenerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The URLs to short
	Urls []string `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *URLShortenerRequest) Reset() {
	*x = URLShortenerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_v1alpha1_url_shortener_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLShortenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLShortenerRequest) ProtoMessage() {}

func (x *URLShortenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1alpha1_url_shortener_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLShortenerRequest.ProtoReflect.Descriptor instead.
func (*URLShortenerRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_v1alpha1_url_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *URLShortenerRequest) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

// The response for shortening some URLs
type URLShortenerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Result of each shortening
	Results []*URLShortenerResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *URLShortenerResponse) Reset() {
	*x = URLShortenerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_v1alpha1_url_shortener_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLShortenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLShortenerResponse) ProtoMessage() {}

func (x *URLShortenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1alpha1_url_shortener_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLShortenerResponse.ProtoReflect.Descriptor instead.
func (*URLShortenerResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_v1alpha1_url_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *URLShortenerResponse) GetResults() []*URLShortenerResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type URLShortenerResponse_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The short URL generated from the shortening
	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	// The original long URL from the shortening
	LongUrl string `protobuf:"bytes,2,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
}

func (x *URLShortenerResponse_Result) Reset() {
	*x = URLShortenerResponse_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_v1alpha1_url_shortener_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLShortenerResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLShortenerResponse_Result) ProtoMessage() {}

func (x *URLShortenerResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1alpha1_url_shortener_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLShortenerResponse_Result.ProtoReflect.Descriptor instead.
func (*URLShortenerResponse_Result) Descriptor() ([]byte, []int) {
	return file_proto_api_v1alpha1_url_shortener_proto_rawDescGZIP(), []int{1, 0}
}

func (x *URLShortenerResponse_Result) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *URLShortenerResponse_Result) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

var File_proto_api_v1alpha1_url_shortener_proto protoreflect.FileDescriptor

var file_proto_api_v1alpha1_url_shortener_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2f, 0x75, 0x72, 0x6c, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x77, 0x65, 0x62, 0x65, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x22, 0x29, 0x0a, 0x13, 0x55, 0x52, 0x4c, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73,
	0x22, 0xac, 0x01, 0x0a, 0x14, 0x55, 0x52, 0x4c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a, 0x07, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x38, 0x2e, 0x77, 0x65, 0x62,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x55, 0x52, 0x4c, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0x40, 0x0a,
	0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x55, 0x72, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x6e, 0x67, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x32,
	0x83, 0x01, 0x0a, 0x0d, 0x55, 0x52, 0x4c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x69, 0x6e,
	0x67, 0x12, 0x72, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x30,
	0x2e, 0x77, 0x65, 0x62, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x55, 0x52, 0x4c,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x31, 0x2e, 0x77, 0x65, 0x62, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x65, 0x72, 0x69, 0x6e,
	0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x55,
	0x52, 0x4c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x57, 0x65, 0x62, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x65, 0x72, 0x69,
	0x6e, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2d, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x3b, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_api_v1alpha1_url_shortener_proto_rawDescOnce sync.Once
	file_proto_api_v1alpha1_url_shortener_proto_rawDescData = file_proto_api_v1alpha1_url_shortener_proto_rawDesc
)

func file_proto_api_v1alpha1_url_shortener_proto_rawDescGZIP() []byte {
	file_proto_api_v1alpha1_url_shortener_proto_rawDescOnce.Do(func() {
		file_proto_api_v1alpha1_url_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_api_v1alpha1_url_shortener_proto_rawDescData)
	})
	return file_proto_api_v1alpha1_url_shortener_proto_rawDescData
}

var file_proto_api_v1alpha1_url_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_api_v1alpha1_url_shortener_proto_goTypes = []interface{}{
	(*URLShortenerRequest)(nil),         // 0: webengineering.api.v1alpha1.URLShortenerRequest
	(*URLShortenerResponse)(nil),        // 1: webengineering.api.v1alpha1.URLShortenerResponse
	(*URLShortenerResponse_Result)(nil), // 2: webengineering.api.v1alpha1.URLShortenerResponse.Result
}
var file_proto_api_v1alpha1_url_shortener_proto_depIdxs = []int32{
	2, // 0: webengineering.api.v1alpha1.URLShortenerResponse.results:type_name -> webengineering.api.v1alpha1.URLShortenerResponse.Result
	0, // 1: webengineering.api.v1alpha1.URLShortening.ShortURLs:input_type -> webengineering.api.v1alpha1.URLShortenerRequest
	1, // 2: webengineering.api.v1alpha1.URLShortening.ShortURLs:output_type -> webengineering.api.v1alpha1.URLShortenerResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_api_v1alpha1_url_shortener_proto_init() }
func file_proto_api_v1alpha1_url_shortener_proto_init() {
	if File_proto_api_v1alpha1_url_shortener_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_api_v1alpha1_url_shortener_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URLShortenerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_v1alpha1_url_shortener_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URLShortenerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_v1alpha1_url_shortener_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URLShortenerResponse_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_api_v1alpha1_url_shortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_v1alpha1_url_shortener_proto_goTypes,
		DependencyIndexes: file_proto_api_v1alpha1_url_shortener_proto_depIdxs,
		MessageInfos:      file_proto_api_v1alpha1_url_shortener_proto_msgTypes,
	}.Build()
	File_proto_api_v1alpha1_url_shortener_proto = out.File
	file_proto_api_v1alpha1_url_shortener_proto_rawDesc = nil
	file_proto_api_v1alpha1_url_shortener_proto_goTypes = nil
	file_proto_api_v1alpha1_url_shortener_proto_depIdxs = nil
}
