// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: proto/api/v1alpha1/url_shortener.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A request of shortening a number of URLs
type ShortURLsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The URLs to short
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ShortURLsRequest) Reset() {
	*x = ShortURLsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_v1alpha1_url_shortener_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLsRequest) ProtoMessage() {}

func (x *ShortURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1alpha1_url_shortener_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLsRequest.ProtoReflect.Descriptor instead.
func (*ShortURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_v1alpha1_url_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortURLsRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// The response for shortening some URLs
type ShortURLsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Result of each shortening
	//
	// Types that are assignable to Result:
	//	*ShortURLsResponse_Success_
	//	*ShortURLsResponse_Error_
	Result isShortURLsResponse_Result `protobuf_oneof:"result"`
}

func (x *ShortURLsResponse) Reset() {
	*x = ShortURLsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_v1alpha1_url_shortener_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLsResponse) ProtoMessage() {}

func (x *ShortURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1alpha1_url_shortener_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLsResponse.ProtoReflect.Descriptor instead.
func (*ShortURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_v1alpha1_url_shortener_proto_rawDescGZIP(), []int{1}
}

func (m *ShortURLsResponse) GetResult() isShortURLsResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *ShortURLsResponse) GetSuccess() *ShortURLsResponse_Success {
	if x, ok := x.GetResult().(*ShortURLsResponse_Success_); ok {
		return x.Success
	}
	return nil
}

func (x *ShortURLsResponse) GetError() *ShortURLsResponse_Error {
	if x, ok := x.GetResult().(*ShortURLsResponse_Error_); ok {
		return x.Error
	}
	return nil
}

type isShortURLsResponse_Result interface {
	isShortURLsResponse_Result()
}

type ShortURLsResponse_Success_ struct {
	// Success on the URL shortening
	Success *ShortURLsResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type ShortURLsResponse_Error_ struct {
	// Error on the URL shortening
	Error *ShortURLsResponse_Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ShortURLsResponse_Success_) isShortURLsResponse_Result() {}

func (*ShortURLsResponse_Error_) isShortURLsResponse_Result() {}

type ShortURLsResponse_Success struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The short URL generated from the shortening
	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	// The original long URL from the shortening
	LongUrl string `protobuf:"bytes,2,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
}

func (x *ShortURLsResponse_Success) Reset() {
	*x = ShortURLsResponse_Success{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_v1alpha1_url_shortener_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLsResponse_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLsResponse_Success) ProtoMessage() {}

func (x *ShortURLsResponse_Success) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1alpha1_url_shortener_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLsResponse_Success.ProtoReflect.Descriptor instead.
func (*ShortURLsResponse_Success) Descriptor() ([]byte, []int) {
	return file_proto_api_v1alpha1_url_shortener_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ShortURLsResponse_Success) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *ShortURLsResponse_Success) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

type ShortURLsResponse_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The original URL that generated the error
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// The error that happened while trying to shorten the URL
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ShortURLsResponse_Error) Reset() {
	*x = ShortURLsResponse_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_v1alpha1_url_shortener_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortURLsResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURLsResponse_Error) ProtoMessage() {}

func (x *ShortURLsResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_v1alpha1_url_shortener_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURLsResponse_Error.ProtoReflect.Descriptor instead.
func (*ShortURLsResponse_Error) Descriptor() ([]byte, []int) {
	return file_proto_api_v1alpha1_url_shortener_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ShortURLsResponse_Error) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ShortURLsResponse_Error) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_api_v1alpha1_url_shortener_proto protoreflect.FileDescriptor

var file_proto_api_v1alpha1_url_shortener_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2f, 0x75, 0x72, 0x6c, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x77, 0x65, 0x62, 0x65, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x22, 0x24, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52,
	0x4c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0xb3, 0x02, 0x0a, 0x11,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x52, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x36, 0x2e, 0x77, 0x65, 0x62, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x65, 0x72,
	0x69, 0x6e, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x4c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x77, 0x65, 0x62, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x65, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x1a, 0x41, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x6c,
	0x6f, 0x6e, 0x67, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c,
	0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x1a, 0x2f, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x32, 0x81, 0x01, 0x0a, 0x0d, 0x55, 0x52, 0x4c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x69, 0x6e, 0x67, 0x12, 0x70, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x73,
	0x12, 0x2d, 0x2e, 0x77, 0x65, 0x62, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x65, 0x72, 0x69, 0x6e,
	0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2e, 0x2e, 0x77, 0x65, 0x62, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x65, 0x72, 0x69, 0x6e, 0x67,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x57, 0x65, 0x62, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x65, 0x72, 0x69,
	0x6e, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2d, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x3b, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_api_v1alpha1_url_shortener_proto_rawDescOnce sync.Once
	file_proto_api_v1alpha1_url_shortener_proto_rawDescData = file_proto_api_v1alpha1_url_shortener_proto_rawDesc
)

func file_proto_api_v1alpha1_url_shortener_proto_rawDescGZIP() []byte {
	file_proto_api_v1alpha1_url_shortener_proto_rawDescOnce.Do(func() {
		file_proto_api_v1alpha1_url_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_api_v1alpha1_url_shortener_proto_rawDescData)
	})
	return file_proto_api_v1alpha1_url_shortener_proto_rawDescData
}

var file_proto_api_v1alpha1_url_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_api_v1alpha1_url_shortener_proto_goTypes = []interface{}{
	(*ShortURLsRequest)(nil),          // 0: webengineering.api.v1alpha1.ShortURLsRequest
	(*ShortURLsResponse)(nil),         // 1: webengineering.api.v1alpha1.ShortURLsResponse
	(*ShortURLsResponse_Success)(nil), // 2: webengineering.api.v1alpha1.ShortURLsResponse.Success
	(*ShortURLsResponse_Error)(nil),   // 3: webengineering.api.v1alpha1.ShortURLsResponse.Error
}
var file_proto_api_v1alpha1_url_shortener_proto_depIdxs = []int32{
	2, // 0: webengineering.api.v1alpha1.ShortURLsResponse.success:type_name -> webengineering.api.v1alpha1.ShortURLsResponse.Success
	3, // 1: webengineering.api.v1alpha1.ShortURLsResponse.error:type_name -> webengineering.api.v1alpha1.ShortURLsResponse.Error
	0, // 2: webengineering.api.v1alpha1.URLShortening.ShortURLs:input_type -> webengineering.api.v1alpha1.ShortURLsRequest
	1, // 3: webengineering.api.v1alpha1.URLShortening.ShortURLs:output_type -> webengineering.api.v1alpha1.ShortURLsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_api_v1alpha1_url_shortener_proto_init() }
func file_proto_api_v1alpha1_url_shortener_proto_init() {
	if File_proto_api_v1alpha1_url_shortener_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_api_v1alpha1_url_shortener_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_v1alpha1_url_shortener_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_v1alpha1_url_shortener_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLsResponse_Success); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_v1alpha1_url_shortener_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortURLsResponse_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_api_v1alpha1_url_shortener_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ShortURLsResponse_Success_)(nil),
		(*ShortURLsResponse_Error_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_api_v1alpha1_url_shortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_api_v1alpha1_url_shortener_proto_goTypes,
		DependencyIndexes: file_proto_api_v1alpha1_url_shortener_proto_depIdxs,
		MessageInfos:      file_proto_api_v1alpha1_url_shortener_proto_msgTypes,
	}.Build()
	File_proto_api_v1alpha1_url_shortener_proto = out.File
	file_proto_api_v1alpha1_url_shortener_proto_rawDesc = nil
	file_proto_api_v1alpha1_url_shortener_proto_goTypes = nil
	file_proto_api_v1alpha1_url_shortener_proto_depIdxs = nil
}
